version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "8001:8001"
    depends_on:
      - service
    env_file:
      - ./frontend/env_files/.env.production
  service:
    build: ./service
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - ./service/env_files/.env.production
  mongo:
    image: mongo
